### PR TITLE
Role aem-cms: Mark configuration parameters that contain sensitive data so they get encrypted in model export YAML files.

### PR DESCRIPTION
**Pull request by stefanseifert**

### CODE REVIEW

**Comment by tobias-richter** [comment]
Sadly there are several problems which cause this PR to not work

## Problem 1 - Format

The format of the encrypted value is wrong.

Actual:
```
config:
  quickstart:
    adminUser:
      password: |-
        !vault
        $ANSIBLE_VAULT;1.1;AES256
        [...DATA...]
```

Expected:
```
config:
  quickstart:
    adminUser:
      password: !vault |
                $ANSIBLE_VAULT;1.1;AES256
                [...DATA...]
```

The vaule must begin with `!vault`, folloed by a space and `|` to indicate it is a multiline string.

## Problem - Decryption

Ansible can not read the vault value.
Even when i format the value as it should be (vault! | ...) i am getting the error.
```
FAILED! => {"msg": "the field 'args' has an invalid value ([]), and could not be converted to an dict.The error was: Invalid padding bytes. [....]"
```

I played a little bit with the `CYPHER_ALGO` from https://github.com/wcm-io-devops/conga-ansible-plugin/blob/develop/conga-ansible-plugin/src/main/java/net/wedjaa/ansible/vault/crypto/decoders/implementation/CypherAES256.java#L46 but i was not able to get it working.
For reference, the encryption in ansible seems to be implemented here:
* https://github.com/ansible/ansible/blob/stable-2.4/lib/ansible/parsing/vault/__init__.py#L1248-L1266 and
* https://github.com/ansible/ansible/blob/stable-2.4/lib/ansible/parsing/vault/__init__.py#L1205-L1215 and
* https://github.com/ansible/ansible/blob/stable-2.4/lib/ansible/parsing/vault/__init__.py#L1220-L1245

which seems to match the specifications which can be found here https://docs.ansible.com/ansible/2.4/vault.html#vault-payload-format-1-1.

## Problem  - conga facts support

[conga facts](https://github.com/wcm-io-devops/ansible-conga-facts) currently does not support vault encrypted strings.
Luckily this issue was an easy one. I implemented the support by using the common ansible data loader.
See https://github.com/wcm-io-devops/ansible-conga-facts/compare/feature/support-for-vault-encrypted-properties

**Comment by tobias-richter** [comment]
It seems that the vault files created by https://github.com/wcm-io-devops/conga-ansible-plugin can not be read by ansible.

But: the conga-ansible-plugin can read vaults created via ansible-vault

I created a test branch for development: 
https://github.com/wcm-io-devops/conga-ansible-plugin/tree/feature/ansible-vault-testing

Within this branch I changed the src/test/resources/vault-sample-wedjaa/test-vault.yml to 
```
source: net.wedjaa.ansible.vault.ProvisioningInfo
apiClientId: The provisioner ClientId
apiPassword: The secret password
apiUser: Secret User
```
because the original file `!net.wedjaa.ansible.vault.ProvisioningInfo`  can not be loaded by ansible (constructor for `net.wedjaa.ansible.vault.ProvisioningInfo`) is missing.

I added a new Unit-Test which will create `conga-ansible-plugin/encoded-test-vault.yml`
This can currently not be loaded by ansible vault:
```
ansible-vault view --vault-password-file=.vault_pass encoded-test-vault.yml
```
This will also result in 'invalid padding bytes' error
```
ERROR! Unexpected Exception, this is probably a bug: Invalid padding bytes.
```

I also added a playbook for testing this:
```
ansible-playbook test-playbook.yml
```
This playbook will:
* load the variables from `src/test/resources/vault-sample-wedjaa/test-vault.yml`
* output and test them
* load the variables from `encoded-test-vault.yml`  (the file generated from the unit-tests)
* output and test them.

The second test will currently fail because ansible vault is not able to decrypt the file.

So for development you can use (within the `conga-ansible-plugin` folder):
```
mvn clean install && ansible-vault view --vault-password-file=.vault_pass encoded-test-vault.yml
``` 
or
```
mvn clean install && ansible-playbook test-playbook.yml
```
for testing

**Comment by stefanseifert** [comment]
concerning "Problem 1 - Format" - following https://stackoverflow.com/a/21699210 there are different types of "block chomping" indicators in YAML file format.
the actual format should be semantically identical to the expected - perhaps except an additional whitespace after "!vault". perhaps this is not a problem at all, but only a follow-up problem from problem 2 - decryption?

**Comment by tobias-richter** [comment]
Thanks for the feedback regarding the ansible version.
I was able to decrypt the vault file generated by the conga-ansible-plugin but only when cryptography and pycrypt are not installed. I think there is a problem with the ansible dependencies of these tools.

I was also able to decrypt the string value rendered into the model.yaml - but only when i change the format to 

```
quickstart:
  adminUser:
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      [....]
```

The `!vault` tells the parser that this has to be interpreted as a vault. It seems that this is part of the pyyaml implementation. Have a look at:

http://pyyaml.org/wiki/PyYAMLDocumentation under "Constructors, representers, resolvers"

**Comment by stefanseifert** [comment]
ah , learned something new about the YAML file format.
i've updated the ansible plugin implementation to export is using such a "!vault" tag - now it looks identical exception one additional "-" which skips the first newline - hopefully it still works.

**Comment by tobias-richter** [comment]
I can confirm, that the format with `!vault | -`  is working.
But we have to investigate and solve the problems with the `cryptography` and `pycrypt` extensions before we should merge this branch.

At the moment i was only able to decrypt the vaults from the conga-ansible-plugin when the ansible vault implementation is used. Since Ansible itself require the cryptography library when installed over PIP we can not provide a stable environment for the users.

**Comment by tobias-richter** [comment]
@stefanseifert with your change in https://github.com/wcm-io-devops/conga-ansible-plugin/commit/67a3a2b052dd4aa97d3a399dfecbd55042dda8fa this is now completely working with
* Ansible decryption
* cryptography based decryption
* pycrypt based decryption.

I tested this with:
* 2.3.2.0
* 2.4.0.0
* 2.4.1.0
* 2.4.2.0
* 2.4.3.0
* 2.4.4.0
* 2.5.0.0
* 2.5.1.0
* 2.5.2.0

I created https://github.com/wcm-io-devops/ansible-conga-facts/pull/4 in order to support the `!vault` format.

**Pull request merged**
