### PR TITLE
Sync dispatcher configuration with Adobe AEM project archetype 39

### PR DESCRIPTION
**Pull request by bellackn**
The local dispatcher validation tooling from Adobe does not work anymore because the immutable files look different nowadays.

### CODE REVIEW

**Comment by stefanseifert** [comment]
i are you sure the immutable files from which we only generate a copy of within the aem-definitions are used at all by cloud manager? i was always under the impression those are ignored and only the actually generated ones by us are picked up.

otherwise outdated features in those will affect hundreds of projects: most of non wcm.io projects are based on AEM archetype, and i assume most of them never update those immutable files after the project was created. all those would break once adobe introduced a change that's based on updated immutable files in the archetype.

however, of course it makes sense to update them. but, as already commented in https://github.com/wcm-io-devops/conga-aem-definitions/pull/76, there is more work around updating to latest archetype. besides updating the immutable files, we also need to check which of the changes in default.vhost and default_filters.any and probably other files should be translated to actual changes in our CONGA templates or default configuration in the role file.

we have to go through all changes of archetype 36, 37, 38, 39, because our last sync in march was with archetype 35.

**Comment by bellackn** [comment]
> are you sure the immutable files from which we only generate a copy of within the aem-definitions are used at all by cloud manager?

no, i don't think they are used by cloud manager. but the local dispatcher validation tools don't work when those files were changed. there is an open adobe ticket where i asked about this.

as a workaround, we can just skip the local validation and run the dispatcher in docker without prevalidating the configs.

> we have to go through all changes of archetype 36, 37, 38, 39, because our last sync in march was with archetype 35.

then let's do this when there's a more urgent need that cannot be easily worked around. ;)

**Review by tobias-richter — APPROVED** [review]
I can not really judge all changes but since this is only a sync this PR should be ok or am I wrong?

**Comment by stefanseifert** [comment]
i've gone trough all changes that have to be transferred to our CONGA templates/role from https://github.com/adobe/aem-project-archetype/compare/aem-project-archetype-35...aem-project-archetype-39

were not that much, see commit https://github.com/wcm-io-devops/conga-aem-definitions/pull/82/commits/29d6058c83ea75bc228120e13fe6cde9a68c112a

the only thing that is left are the changes from https://github.com/adobe/aem-project-archetype/pull/937 - those changes are placed a bit directly in default.vhost, and we cannot express them 1:1 e.g. with the existing `httpd.headers.cacheControl` configuration option we have currently.
@tobias-richter  WDYT?

**Comment by stefanseifert** [comment]
i've left out the https://github.com/adobe/aem-project-archetype/pull/937 for now - they seem to be very specialized, we'll leave such type of cache fine-tuning to the projects.

**Pull request merged**
