### PR TITLE
use LocationMatch directive instead of Location ~ to avoid broken CORS section

### PR DESCRIPTION
**Pull request by BerSomBen**

### CODE REVIEW

**Comment by tobias-richter** [comment]
@BerSomBen please update the changes.xml in the root too. 
You can use these lines as a template: https://github.com/wcm-io-devops/conga-aem-definitions/blob/develop/changes.xml#L73-L75

**Comment by BerSomBen** [comment]
updated changes.xml

**Comment by stefanseifert** [comment]
thanks for the contribution!

**Comment by tobias-richter** [comment]
@BerSomBen congratulations :)

**Pull request merged**
