### PR TITLE
Add dispatcher.customConfig.after for role aem-dispatcher to allow cu…

### PR DESCRIPTION
**Pull request by tobias-richter**
…stom configurations in dispatcher.conf

@stefanseifert i was struggling with myself if this configuration option should be within the httpd or the dispatcher scope. Please let me know if we should change the scope/wording

### CODE REVIEW

**Comment by stefanseifert** [comment]
what is the use case for this PR? the current dispatcher.conf part is already a bit polluted containing more than only the dispatcher part. is this additional config block you want to add in any case related to configuring the dispatcher module?

every new parameter we define needs to be defined in the config block of the role definition as well - this it the main "documentation" of the role.

**Comment by tobias-richter** [comment]
I fixed the missing documentation and added an example.
The idea behind this PR was to provide a way to make the dispatcher.conf somehow configurable.
The configuration option would be more or less used to apply configuration options for all vhosts like already present with the "AddType" definitions.

But perhaps the better way would be to create a "common.conf" and move https://github.com/wcm-io-devops/conga-aem-definitions/blob/develop/conga-aem-definitions/src/main/templates/aem-dispatcher/common/dispatcher.conf.hbs#L49-L85 to this new common configuration file and a customizable configuration option there.

The usecase on my side is to place a fix for all vhosts that allow client side caching for gzipped resources when using the etag mechanism.
Example:
```
dispatcher:
    customConfig.after: |
      # remove gzip ending to allow not modified responses
      SetEnvIf           If-None-Match "-gzip\"$" request_etag=gzip
      RequestHeader edit If-None-Match "(.+)-gzip\"$" "$1\""
      Header edit        ETag     "(.+(?<!-gzip))\"$" "$1-gzip\"" "expr=reqenv('request_etag') == 'gzip' || resp('Content-Encoding') == 'gzip'"
```

**Comment by stefanseifert** [comment]
> But perhaps the better way would be to create a "common.conf"

yes, i think something like this would be definitely better - instead of making the current mess in dispatcher.conf worse by making it configurable. and this would solve the naming issues as well - it does not belong to "dispatcher" at all.

**Comment by tobias-richter** [comment]
Closing PR

**Pull request closed without merging**
